# Generated by Django 5.2.17 on 2026-09-10 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('candidates', '0001_initial'),
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('application_submitted', 'Application submitted'), ('application_withdrawn', 'Application withdrawn'), ('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_completed', 'Interview completed')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(max_length=1000)),
                ('is_read', models.BooleanField(default=False)),
                ('event_key', models.CharField(editable=False, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='applications.application')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='candidates.candidateprofile')),
                ('interview', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='interviews.interview')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['candidate', '-created_at'], name='notificatio_candida_7f845a_idx'), models.Index(fields=['candidate', 'is_read', '-created_at'], name='notificatio_candida_7185c2_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('notification_type__in', ('application_submitted', 'application_withdrawn', 'interview_scheduled', 'interview_rescheduled', 'interview_cancelled', 'interview_completed'))), name='notification_type_valid')],
            },
        ),
    ]
