# Generated by Django 5.2.17 on 2026-09-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('candidates', '0001_initial'),
        ('interviews', '0001_initial'),
        ('jobs', '0001_initial'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_type_valid',
        ),
        migrations.AddField(
            model_name='notification',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_notifications', to='jobs.job'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('application_submitted', 'Application submitted'), ('application_withdrawn', 'Application withdrawn'), ('interview_scheduled', 'Interview scheduled'), ('interview_rescheduled', 'Interview rescheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_completed', 'Interview completed'), ('job_alert_match', 'Job alert match')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(('notification_type__in', ('application_submitted', 'application_withdrawn', 'interview_scheduled', 'interview_rescheduled', 'interview_cancelled', 'interview_completed', 'job_alert_match'))), name='notification_type_valid'),
        ),
    ]
