# Generated by Django 5.2.17 on 2026-09-08 04:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_name', models.CharField(max_length=255)),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('mode', models.CharField(choices=[('online', 'Online'), ('phone', 'Phone'), ('in_person', 'In person')], max_length=20)),
                ('meeting_link', models.URLField(blank=True, max_length=1000)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application')),
            ],
            options={
                'ordering': ('scheduled_at', 'id'),
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='interviews__status_39545c_idx'), models.Index(fields=['application', 'scheduled_at'], name='interviews__applica_aa1851_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration_minutes__gt', 0)), name='interview_duration_positive')],
            },
        ),
    ]
