# Generated by Django 5.2.17 on 2026-09-21 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Job Alert', max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('work_mode', models.CharField(blank=True, choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('employment_type', models.CharField(blank=True, choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('temporary', 'Temporary')], max_length=50)),
                ('experience_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to='candidates.candidateprofile')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['candidate', '-created_at'], name='job_alerts__candida_189011_idx'), models.Index(fields=['candidate', 'is_active'], name='job_alerts__candida_7aab28_idx'), models.Index(fields=['is_active', '-updated_at'], name='job_alerts__is_acti_7312f9_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('experience_min__isnull', True), ('experience_max__isnull', True), ('experience_min__lte', models.F('experience_max')), _connector='OR'), name='job_alert_experience_range_valid'), models.CheckConstraint(condition=models.Q(('salary_min__isnull', True), ('salary_max__isnull', True), ('salary_min__lte', models.F('salary_max')), _connector='OR'), name='job_alert_salary_range_valid')],
            },
        ),
    ]
