# Generated by Django 5.2.17 on 2026-08-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('employment_type', models.CharField(max_length=50)),
                ('work_mode', models.CharField(choices=[('onsite', 'On-site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=10)),
                ('experience_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('experience_max', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('salary_min', models.PositiveBigIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveBigIntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('application_url', models.URLField(max_length=1000)),
                ('source', models.CharField(max_length=100)),
                ('source_job_id', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-posted_at', '-id'),
                'indexes': [models.Index(fields=['is_active', '-posted_at'], name='jobs_job_is_acti_e01e1d_idx'), models.Index(fields=['work_mode'], name='jobs_job_work_mo_424767_idx'), models.Index(fields=['employment_type'], name='jobs_job_employm_743f88_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_job_id'), name='unique_job_per_source'), models.CheckConstraint(condition=models.Q(('experience_max__isnull', True), ('experience_min__isnull', True), ('experience_max__gte', models.F('experience_min')), _connector='OR'), name='job_experience_range_valid'), models.CheckConstraint(condition=models.Q(('salary_max__isnull', True), ('salary_min__isnull', True), ('salary_max__gte', models.F('salary_min')), _connector='OR'), name='job_salary_range_valid')],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='candidates.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='jobs.job')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'constraints': [models.UniqueConstraint(fields=('candidate', 'job'), name='unique_candidate_saved_job')],
            },
        ),
    ]
