# Generated by Django 5.2.17 on 2026-09-29 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_provider_last_seen_at_ingestionrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='rejection_reasons',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
