# Generated by Django 5.2.17 on 2026-09-30 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_ingestionrun_rejection_reasons'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20),
        ),
    ]
